// Seal the staged CLI (app/build/cli, produced by stage-cli.mjs) into its own
// ASAR under Electron resources. The archive keeps normal Node package paths —
// including @scope/package — opaque to AppX/MakeAppx, avoiding the RC8 `%40scope`
// rewrite while preserving the runtime's real production dependency closure.
//
// A tiny loose launcher remains at resources/cli/dist/launch.js so the desktop's
// long-standing bundled-entry path does not change. It imports the real main.js
// from resources/cli.asar; no loose node_modules tree is shipped.

const { createPackage } = require('@electron/asar')
const { existsSync, mkdirSync, rmSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')

exports.default = async function afterPack(context) {
  const { appOutDir, electronPlatformName, packager } = context
  const src = join(__dirname, '..', 'build', 'cli')
  if (!existsSync(join(src, 'dist', 'launch.js')) || !existsSync(join(src, 'dist', 'main.js')) || !existsSync(join(src, 'node_modules'))) {
    throw new Error(`after-pack: ${src} runtime is incomplete — run "npm run stage-cli" first`)
  }

  const resources =
    electronPlatformName === 'darwin'
      ? join(appOutDir, `${packager.appInfo.productFilename}.app`, 'Contents', 'Resources')
      : join(appOutDir, 'resources')

  const archive = join(resources, 'cli.asar')
  const looseRoot = join(resources, 'cli')
  rmSync(archive, { force: true })
  rmSync(looseRoot, { recursive: true, force: true })

  await createPackage(src, archive)
  if (!existsSync(archive)) throw new Error('after-pack: cli.asar was not created')

  const launcherDir = join(looseRoot, 'dist')
  mkdirSync(launcherDir, { recursive: true })
  writeFileSync(
    join(launcherDir, 'launch.js'),
    [
      '// Generated by app/scripts/after-pack.cjs — do not edit.',
      'if (process.versions.electron) process.argv.splice(1, 1)',
      "import('../../cli.asar/dist/main.js').catch(err => {",
      '  process.stderr.write(String(err?.message ?? err) + \'\\n\')',
      '  process.exit(1)',
      '})',
      '',
    ].join('\n'),
  )

  console.log(`after-pack: staged CLI sealed -> ${archive}`)
}
