// Stage a complete copy of the root Metrora runtime into app/build/cli so
// electron-builder can seal it into a CLI-specific ASAR during afterPack.
//
// Keep the runtime's normal external production dependencies here. Packaging
// them inside cli.asar preserves scoped npm paths such as @scope/package without
// exposing those path segments to MakeAppx, which had rewritten them to %40scope
// in the RC8 loose-file payload.
//
//   build/cli/package.json
//   build/cli/THIRD_PARTY_NOTICES.md
//   build/cli/LICENSES/Apache-2.0.txt
//   build/cli/LICENSES/UPSTREAM-MIT.txt
//   build/cli/dist/cli.js
//   build/cli/dist/main.js
//   build/cli/dist/desktop-local-state.js
//   build/cli/dist/desktop-reviewed-production.js
//   build/cli/dist/desktop-share-runtime.js
//   build/cli/dist/launch.js
//   build/cli/node_modules/
//
// The production closure is copied out of the already-installed root
// node_modules (offline, no reinstall). Run the root CLI build first so dist/ is
// fresh — the app `stage-cli` script does exactly that.

import { execFileSync } from 'node:child_process'
import { cpSync, copyFileSync, existsSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url)) // app/scripts
const appDir = join(here, '..') // app
const root = join(appDir, '..') // repo root
const dist = join(root, 'dist')
const rootModules = join(root, 'node_modules')
const stage = join(appDir, 'build', 'cli')
const emittedFiles = ['cli.js', 'main.js', 'desktop-local-state.js', 'desktop-reviewed-production.js', 'desktop-share-runtime.js']
const noticeFiles = [
  ['THIRD_PARTY_NOTICES.md', 'THIRD_PARTY_NOTICES.md'],
  [join('LICENSES', 'Apache-2.0.txt'), join('LICENSES', 'Apache-2.0.txt')],
  [join('LICENSES', 'UPSTREAM-MIT.txt'), join('LICENSES', 'UPSTREAM-MIT.txt')],
]

for (const file of emittedFiles) {
  if (!existsSync(join(dist, file))) {
    throw new Error(`stage-cli: ${join(dist, file)} is missing — build the root CLI first`)
  }
}
for (const [source] of noticeFiles) {
  if (!existsSync(join(root, source))) throw new Error(`stage-cli: required notice ${source} is missing`)
}

rmSync(stage, { recursive: true, force: true })
mkdirSync(join(stage, 'dist'), { recursive: true })
mkdirSync(join(stage, 'LICENSES'), { recursive: true })

copyFileSync(join(root, 'package.json'), join(stage, 'package.json'))
for (const file of emittedFiles) copyFileSync(join(dist, file), join(stage, 'dist', file))
for (const [source, destination] of noticeFiles) copyFileSync(join(root, source), join(stage, destination))

// Desktop-app launch shim. In the staged layout it is also used for a plain-Node
// smoke check; afterPack writes an equivalent tiny proxy outside cli.asar so the
// packaged app can keep its stable resources/cli/dist/launch.js entry path.
const launch = join(stage, 'dist', 'launch.js')
writeFileSync(
  launch,
  [
    '// Generated by app/scripts/stage-cli.mjs — do not edit.',
    'if (process.versions.electron) process.argv.splice(1, 1)',
    "import('./main.js').catch(err => {",
    '  process.stderr.write(String(err?.message ?? err) + \'\\n\')',
    '  process.exit(1)',
    '})',
    '',
  ].join('\n'),
)

// `npm ls` prints the tree to stdout even when it exits non-zero on peer/
// extraneous warnings, so capture stdout regardless of exit code.
let listed = ''
try {
  // Execute npm's JavaScript entry point with the current Node binary. Windows
  // exposes npm as a .cmd shim, which execFile cannot launch without a shell.
  const npmCli = process.env.npm_execpath
  if (!npmCli) throw new Error('npm_execpath is unavailable')
  listed = execFileSync(process.execPath, [npmCli, 'ls', '--omit=dev', '--all', '--parseable'], {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
} catch (err) {
  listed = err.stdout ? String(err.stdout) : ''
}

// Every parseable line is an absolute path to a production package instance.
// Map each back to its top-level node_modules entry (`name` or `@scope/name`),
// then copy those dirs whole — a package's own nested node_modules comes with
// it, which is exactly the closure it needs.
const prefix = rootModules.replaceAll('\\', '/') + '/'
const comparisonPrefix = process.platform === 'win32' ? prefix.toLowerCase() : prefix
const topLevel = new Set()
for (const line of listed.split('\n')) {
  const normalizedLine = line.trim().replaceAll('\\', '/')
  const comparisonLine = process.platform === 'win32' ? normalizedLine.toLowerCase() : normalizedLine
  if (!comparisonLine.startsWith(comparisonPrefix)) continue
  const rest = normalizedLine.slice(prefix.length)
  const match = rest.match(/^(@[^/]+\/[^/]+|[^/]+)/)
  if (match) topLevel.add(match[1])
}
if (topLevel.size === 0) {
  throw new Error('stage-cli: production dependency closure is empty — is the root `npm install`ed?')
}

mkdirSync(join(stage, 'node_modules'), { recursive: true })
for (const pkg of topLevel) {
  const src = join(rootModules, pkg)
  if (!existsSync(src) || !statSync(src).isDirectory()) continue
  cpSync(src, join(stage, 'node_modules', pkg), { recursive: true, dereference: true })
}

// A partially-copied runtime that crashes on import is worse than none: fail the
// build if any external runtime dependency did not land.
const required = [
  'chalk', 'react', 'ink', 'strip-ansi', 'zod', 'undici',
  'selfsigned', 'commander', 'bonjour-service', '@modelcontextprotocol/sdk',
]
const missing = required.filter(pkg => !existsSync(join(stage, 'node_modules', pkg)))
if (missing.length) {
  throw new Error(`stage-cli: staged bundle is missing runtime deps: ${missing.join(', ')}`)
}

// Exercise the staged production closure before Electron packaging. The Store
// workflow separately executes the sealed cli.asar copy with Metrora.exe, so
// both the pre-package closure and the exact AppX runtime are covered.
let versionOutput = ''
try {
  versionOutput = execFileSync(process.execPath, [launch, '--version'], {
    cwd: stage,
    encoding: 'utf8',
    env: { ...process.env, NO_COLOR: '1' },
    timeout: 30_000,
  }).trim()
} catch (error) {
  const stderr = error?.stderr ? String(error.stderr).trim() : ''
  throw new Error(`stage-cli: staged CLI smoke test failed${stderr ? `: ${stderr}` : ''}`)
}
if (!/^\d+\.\d+\.\d+/.test(versionOutput)) {
  throw new Error(`stage-cli: staged CLI returned an unexpected version: ${versionOutput || '<empty>'}`)
}

console.log(`stage-cli: staged ${topLevel.size} production packages, ${emittedFiles.length} runtime files and third-party notices -> ${stage}`)
