// Stage the root Metrora runtime into app/build/cli so electron-builder can ship
// the compatibility CLI and the narrow desktop main-process entries.
//
// `tsup.config.ts` deliberately bundles every production dependency into the
// emitted runtime. Keep the staged Store payload free of a loose node_modules
// tree: AppX packaging may rewrite `@scope` directory segments, which breaks
// Node module resolution after installation. A self-contained JS bundle avoids
// that packaging ambiguity entirely while preserving the public npm launcher.
//
//   build/cli/package.json
//   build/cli/THIRD_PARTY_NOTICES.md
//   build/cli/LICENSES/Apache-2.0.txt
//   build/cli/dist/cli.js
//   build/cli/dist/main.js
//   build/cli/dist/desktop-local-state.js
//   build/cli/dist/desktop-reviewed-production.js
//   build/cli/dist/launch.js

import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url)) // app/scripts
const appDir = join(here, '..') // app
const root = join(appDir, '..') // repo root
const dist = join(root, 'dist')
const stage = join(appDir, 'build', 'cli')
const emittedFiles = ['cli.js', 'main.js', 'desktop-local-state.js', 'desktop-reviewed-production.js']
const noticeFiles = [
  ['THIRD_PARTY_NOTICES.md', 'THIRD_PARTY_NOTICES.md'],
  [join('LICENSES', 'Apache-2.0.txt'), join('LICENSES', 'Apache-2.0.txt')],
]

for (const file of emittedFiles) {
  if (!existsSync(join(dist, file))) {
    throw new Error(`stage-cli: ${join(dist, file)} is missing — build the root CLI first`)
  }
}
for (const [source] of noticeFiles) {
  if (!existsSync(join(root, source))) throw new Error(`stage-cli: required notice ${source} is missing`)
}

rmSync(stage, { recursive: true, force: true })
mkdirSync(join(stage, 'dist'), { recursive: true })
mkdirSync(join(stage, 'LICENSES'), { recursive: true })

copyFileSync(join(root, 'package.json'), join(stage, 'package.json'))
for (const file of emittedFiles) copyFileSync(join(dist, file), join(stage, 'dist', file))
for (const [source, destination] of noticeFiles) copyFileSync(join(root, source), join(stage, destination))

// Desktop-app launch shim (the app spawns this, not cli.js). The packaged app
// runs the CLI with Electron's own binary as Node (ELECTRON_RUN_AS_NODE=1).
// Because process.versions.electron is then set, commander's argv auto-detection
// treats a packaged (non-defaultApp) Electron as `from: 'electron'` and slices
// argv by 1 instead of 2 — leaving this script's own path among the parsed args
// and shifting every real argument. Drop that element before handing off so the
// CLI's `program.parse()` sees the true args. Guarded so the shim also works if
// ever run under plain Node. Kept in the app (not the shared CLI source) so the
// published CLI is untouched.
const launch = join(stage, 'dist', 'launch.js')
writeFileSync(
  launch,
  [
    '// Generated by app/scripts/stage-cli.mjs — do not edit.',
    'if (process.versions.electron) process.argv.splice(1, 1)',
    "import('./main.js').catch(err => {",
    '  process.stderr.write(String(err?.message ?? err) + \'\\n\')',
    '  process.exit(1)',
    '})',
    '',
  ].join('\n'),
)

// Fail during staging if the emitted runtime still needs an external package in
// order to perform the most basic import/Commander startup. This is intentionally
// a local Node check; the Store workflow additionally runs the packaged copy with
// Electron-as-Node so the final distribution layout is exercised too.
let versionOutput = ''
try {
  versionOutput = execFileSync(process.execPath, [launch, '--version'], {
    cwd: stage,
    encoding: 'utf8',
    env: { ...process.env, NO_COLOR: '1' },
    timeout: 30_000,
  }).trim()
} catch (error) {
  const stderr = error?.stderr ? String(error.stderr).trim() : ''
  throw new Error(`stage-cli: bundled CLI smoke test failed${stderr ? `: ${stderr}` : ''}`)
}
if (!/^\d+\.\d+\.\d+/.test(versionOutput)) {
  throw new Error(`stage-cli: bundled CLI returned an unexpected version: ${versionOutput || '<empty>'}`)
}

console.log(`stage-cli: staged self-contained CLI runtime (${emittedFiles.length} emitted files) -> ${stage}`)
